[Main page] 구조 및 뼈대 잡고, 상단 타이틀 static 하게 완성
Jaws-bar/Entry4.0-EntrySystem-Frontend pull request #14
Opened 2019-06-07 07:20 UTC by junu126

오늘 date 값은 완성했으나, 마감일 까지 남은 date는 구현하지 못하였습니다.
제플린에 수정할 요소가 몇 보여서 아직 진행하지 않았습니다.

2019-06-11 11:25 UTC, engolder requested changes
text props를 사용하는 부분만 좀 수정해주시면 될듯

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/default/Common/MainHeadLine.tsx
> +  </MainHeadLineCover>
styled components naming에 대해서 구글링을 좀 해보았는데
https://medium.com/inturn-eng/naming-styled-components-d7097950a245
여기보면
```js
import Header from ‘Components/Header’;
import * as S from ‘./styles';
const Navigation = () => (
  <S.Navigation>
    <Header>{headerContent}</Header>
    <S.Content>{content}</S.Content>
  </S.Navigation>
);
```
이런식으로 하는 것도 하나의 해결방법이라고 소개되어있습니다. 저는 현재 이 방법을 사용중이고 한번 고려해봐도 좋을 듯 합니다.

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/main/MainContentsTitle.tsx
> +      {text[0]}
text의 배열 원소가 있을지 장담할 수 없습니다.
차라리 서로다른 props를 받는게 나아보입니다.

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/main/MainTitles.tsx
> +  const date = dateData < 10 ? `0${dateData}` : dateData;
날짜 연산과 formatting은 pure function으로 만들어서 분리하는 편이 좋아보입니다

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/main/MainTitles.tsx
> +  const date = dateData < 10 ? `0${dateData}` : dateData;
변수명이 명확하지않고 굉장히 햇갈릴 소지가 있어보입니다.(아마 작년에 내가짰겠지 ㅋㅋ)
function으로 분리하면 해결될 문제같네요

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/main/MainTitles.tsx
> +  ];
코드가 아직 완성되지 않은것 같네요??

2019-06-11 11:25 UTC, engolder commented on natuur/src/components/main/constance.ts
> +];
enum을 활용해보아도 좋을 것 같네용

2019-06-11 11:29 UTC, junu126 commented on natuur/src/components/main/MainTitles.tsx
> +  ];
제플린 수정전이라서 다음 개발 진행을 위해 우선 커밋했습니다!

2019-06-11 11:30 UTC, junu126 commented on natuur/src/components/main/MainContentsTitle.tsx
> +      {text[0]}
수정하도록 하겠습니다.

2019-06-11 12:48 UTC, junu126 commented on natuur/src/components/default/Common/MainHeadLine.tsx
> +  </MainHeadLineCover>
저번부터 Style과 Component가 했갈릴 수 있겠다는 생각을 했었는데, 이런 방법이 있었군요.
그런데 지금 와서 수정하기에는 너무 많은 작업이 될 것 같아요.

Main페이지 완성 후 시간내서 리펙토링 작업 거치도록 하겠습니다.

2019-06-11 12:52 UTC, junu126 commented on natuur/src/components/main/constance.ts
> +];
enum이 배열선언할때 사용할 수 있나요??
구글링을 해도 잘 나오지 않아서요! @engolder

2019-06-11 13:34 UTC, junu126 commented on natuur/src/components/main/MainTitles.tsx
> +  const date = dateData < 10 ? `0${dateData}` : dateData;
수정했습니당

2019-06-12 10:46 UTC, engolder commented on natuur/src/components/main/constance.ts
> +];
아 배열식으로 사용하기 보단 key value로 사용을 해도 괜찮을 것 같다는 의견입니다. 사실 저 코드를 사용하는 부분이 아직 완성되지 않아서 어떻게쓰일진 모르겠지만..

2019-06-12 10:54 UTC, engolder approved these changes

2019-06-12 10:54 UTC, engolder commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +  };
순수함수인데 render영역에 있네요 밖으로 빼주세요

2019-06-13 05:03 UTC, junu126 commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +  };
완료 헀심니당

2019-06-13 13:58 UTC, merged