[Main page] make progress bar component
Jaws-bar/Entry4.0-EntrySystem-Frontend pull request #16
Opened 2019-06-17 03:28 UTC by junu126

ProgressBar 컴포넌트를 완성시켰습니다.

현재 progress가 증가하는 로직을 만들고 있는 중 입니다.

빠른 Code Review 부탁드려요

2019-06-17 06:49 UTC, engolder requested changes

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/constance.ts
>  ];
전체적으로 네이밍이 햇갈리고 각 배열의 index순서가 관련이 있어보이네요 차라리 하나로 묶는게 나을듯

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/ViewClose.tsx
> +export default ViewClose;
쓰지도 않는 컴포넌트가..?

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
>    return { toDayYear, toDayMonth, toDayDate };
왜 네이밍이 today가아니라 toDay죠?

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +  ];
title1, title2보단 title, subtitle처럼 의미가 있는게 낫지않을까요

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +const getFormatDate = ({
formatDate도 문제가 없어보이는데 바꾼이유가있나요

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +const getFormatDate = ({
util함수는 따로 빼서 관리합시다

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/progress/IndexItem.tsx
> +  <IndexCover onClick={() => setTimeStempChecker(timeStempNumber)}>
익명함수가 render로직속에 들어가면 안될 것 같네요. bind메서드를 활용해봅시다

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/progress/IndexItemsBox.tsx
> +export default IndexItemsBox;
IndexItemsBox보다는 IndexItems혹은 IndexItemList가 나을듯 하네요. 실제로 box역할을 하는 것처럼 보이진않으니!

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/timestemp/MainTimeStemp.tsx
> +  </div>
div로 감쌀필요가없어보입니다

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/ViewOpen.tsx
> +        sessionStorage.getItem("token") ? "원서작성 하러가기" : "로그인 하기"
외부 저장소를 사용하는 코드는 분리해서 관린하는편이 좋아보입니다

2019-06-17 06:49 UTC, engolder commented on natuur/src/components/main/viewCase/ViewOpen.tsx
> +      }}
????

2019-06-17 12:40 UTC, junu126 commented on natuur/src/components/main/viewCase/ViewClose.tsx
> +export default ViewClose;
이 컴포넌트는 아직 완성되지 않았습니다! 우선 넣어둔거에요.

2019-06-17 12:40 UTC, junu126 commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
>    return { toDayYear, toDayMonth, toDayDate };
아 인정합니다..

2019-06-17 12:46 UTC, junu126 commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +  ];
이때 변수명을 엄청 만들다보니까 머리가 아파서 저렇게 해둔 것 같아요. 수정하겠습니다.

2019-06-17 13:14 UTC, junu126 commented on natuur/src/components/main/viewCase/titles/MainTitles.tsx
> +const getFormatDate = ({
수정 했습니다.

2019-06-17 13:20 UTC, junu126 commented on natuur/src/components/main/viewCase/progress/IndexItemsBox.tsx
> +export default IndexItemsBox;
네! 수정완료요

2019-06-17 13:27 UTC, junu126 commented on natuur/src/components/main/viewCase/ViewOpen.tsx
> +        sessionStorage.getItem("token") ? "원서작성 하러가기" : "로그인 하기"
새로운거 많이 알아갑니다..ㅠㅠㅠ
수정했어요

2019-06-17 13:29 UTC, junu126 commented on natuur/src/components/main/viewCase/ViewOpen.tsx
> +      }}
임시 데이터 입니다..!

2019-06-17 13:29 UTC, junu126 commented on natuur/src/components/main/viewCase/progress/IndexItem.tsx
> +  <IndexCover onClick={() => setTimeStempChecker(timeStempNumber)}>
수정헀슴니다아ㅏㅇ

2019-06-17 13:40 UTC, junu126 commented on natuur/src/components/main/constance.ts
>  ];
수정 했습니다.

2019-06-18 05:36 UTC, engolder commented on natuur/src/components/main/constance.ts
> +  "2019.11.07 (목) ~ 11.13 (수) 17:00"
`PERIOD_LIST`에 따라서 `TIME_STEMP_DATE`가 나올 수 있을 것 같아요
고로 TIME_STEMP_DATE필요 없어보임

2019-06-18 12:38 UTC, junu126 commented on natuur/src/components/main/constance.ts
> +  "2019.11.07 (목) ~ 11.13 (수) 17:00"
`TIME_STEMP_DATE`를 만약 제거한다면, `TIME_STEMP_DATE`의 문자열에 맞도록 formating을 해줘야 하는데 그렇게 되면 훨씬 더 많은 코드가 생길 것 같아요. 상수로 분리했는데 납둬도 괜찮지 않을까요??

2019-07-10 02:36 UTC, engolder commented on natuur/src/components/main/constance.ts
> +  "2019.11.07 (목) ~ 11.13 (수) 17:00"
네 제거하세요 Dry하지 않습니다

2019-07-12 01:10 UTC, engolder requested changes

2019-07-12 01:10 UTC, engolder commented on natuur/src/lib/utils/main/index.ts
> +  }
열거형 써보는거 어떠십니까 ^^

2019-07-12 01:11 UTC, junu126 commented on natuur/src/lib/utils/main/index.ts
> +  }
나이스

2019-07-12 01:14 UTC, engolder requested changes

2019-07-12 01:14 UTC, engolder commented on natuur/src/lib/utils/main/index.ts
> +    return koreanDate[dayDate];
함수로 만들 필요가 없어보입니다!

2019-07-12 01:20 UTC, engolder requested changes

2019-07-12 01:20 UTC, engolder commented on natuur/src/lib/utils/main/index.ts
> +    const endHourDate = endDate.getHours();
suffix로 date보단 string이 나을것같네요

2019-07-12 01:20 UTC, engolder commented on natuur/src/lib/utils/main/index.ts
> +  function getKoreanDayData(dayDate: number): string {
getTimeStempDate 밖으로, 전역 함수로 등록해야하는게 좋아보입니다. 함수호출시마다 생성될테니..

2019-07-12 01:27 UTC, engolder approved these changes

2019-07-12 01:27 UTC, merged