useEffect 로직 에러 수정
Jaws-bar/Entry4.0-EntrySystem-Frontend pull request #6
Opened 2019-05-10 05:39 UTC by junu126

# redux로 구현하려던 로직을 useState로 구현

처음에는 redux로 App의 class이름을 변경시켜주는 로직을 만들려고 햇으나 useEffect(componenctDidMount)에서 dispatch를 시키는 바람에 무한루프가 발생한다.

그리고 부모 자식관계가 한단계로 이루어 지고 있기 때문에 그냥 setState를 이용해도 된다고 판단함.

2019-05-14 05:49 UTC, engolder requested changes
Current route에 따라서 배경화면 스타일에 변화를 주려는 것 같은데 이 방식에 대해서는 더 좋은 방법이 있을 것 같네요

2019-05-14 05:49 UTC, engolder commented on natuur/src/App.tsx
> +  };
setAppClass를 그대로 사용해도 문제가 없어보입니다

2019-05-14 05:49 UTC, engolder commented on natuur/src/App.tsx
> +            component={() => <Main updateAppClass={updateAppClass} />}
Route 컴포넌트에 props를 전달하기 위해서 component속성에 함수를 넘긴 것 같은데,
> “When you use the component props, the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function to the component attribute, you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component.”

이렇게 하게되면 렌더 함수가 호출될 때 마다 계속해서 새로운 리액트 엘리먼트를 생성합니다.
대신에 [render](https://reacttraining.com/react-router/web/api/Route/render-func) 속성을 사용합시다

2019-05-14 05:49 UTC, engolder commented on natuur/src/container/Info/Info.tsx
>    // componentDidmount
useEffect로 충분히 설명됩니다. 불필요한 주석은 제거해주세요

2019-05-16 11:22 UTC, junu126 commented on natuur/src/App.tsx
> +  };
넹 수정했습니다.

2019-05-16 11:22 UTC, junu126 commented on natuur/src/App.tsx
> +            component={() => <Main updateAppClass={updateAppClass} />}
넹 수정했습니다.

2019-05-16 11:22 UTC, junu126 commented on natuur/src/container/Info/Info.tsx
>    // componentDidmount
넹 수정했습니다.

2019-05-16 11:24 UTC, engolder approved these changes

2019-05-16 11:24 UTC, merged