[Identity verification] 서버 통신 & tostBar 를 제외하고 완성
Jaws-bar/Entry4.0-EntrySystem-Frontend pull request #7
Opened 2019-05-14 14:02 UTC by junu126

서버통신 부분은 아직 서버가 완성되지 않아서 남겨두었습니다.
또 TostBar를 제외하고 모든 로직을 구현했습니다. vue에서 react로 옮기는 작업도 끝났습니다.

`debounce`를 적용시켜보려고 했으나 약 8시간정도를 소비하며 공부하고 여러 방향으로 적용을 시켜보았습니다. 구현도 해보고, 라이브러리도 여러개를 이용해보았지만 결론적으로 해결하지 못하여 우선 PR을 날립니다.

혹시 방법을 알고계시면 알려주세요 ㅠㅠㅠ react + ts + redux + hooks + `debounce`

2019-05-16 11:19 UTC, engolder requested changes
화이팅~~~~~~

2019-05-16 11:19 UTC, engolder commented on natuur/src/container/Authorization/SignUp/SignUp.tsx
> +    setChecked(state);
함수로 감쌀필요없습니다

2019-05-16 11:19 UTC, engolder commented on natuur/src/container/Authorization/SignUp/SignUp.tsx
> +        updateUserEmail(value);
코드의 중복을 피하기 위해서 문자열 리터럴을 사용하면서 3개의 핸들러를 하나로 합치는 것보다는 각각의 핸들러를 사용해주는 편이 좋습니다. 런타임에러를 유발합니다.

2019-05-16 11:19 UTC, engolder commented on natuur/src/App.tsx
> +            exact={true}
shortcut을 바꾼이유가 있나요?

2019-05-16 11:19 UTC, engolder commented on natuur/src/App.tsx
> +          <Route path="/intro" component={() => <Introduce />} exact={true} />
component속성을 사용하면 렌더링시마다 컴포넌트를 재생성하는 큰 비용이 들어갑니다. 대신 render속성을 사용합시다

2019-05-16 11:19 UTC, engolder commented on natuur/src/styles/Authorization/index.ts
> +  border-color: ${(props: any) => props.false && '#a7a7a7'};
false라는 네이밍은 문제가 있어보입니다
1. javascript keyword임
2. boolean변수는 is혹은 on접두로 시작하는 것이 좋을 듯

2019-05-16 11:19 UTC, engolder commented on natuur/src/styles/Authorization/index.ts
> +export const AcceptTermsCheckBoxLabel: any = styled.label`
any타입을 따로 명시해줄 필요가 없어보입니다

2019-05-16 11:19 UTC, engolder commented on natuur/src/styles/Authorization/index.ts
> +  border-color: ${(props: any) => props.false && '#a7a7a7'};
props의 타입을 정의해주세요 interface가 적합해보입니다

2019-05-16 11:19 UTC, engolder commented on natuur/src/components/Authorization/AcceptTerms.tsx
> +  </AcceptTermsComponent>
체크박스는 reuseable컴포넌트로 분리하고, Signup에서 임포트해야할것같습니다. 현재 이 컴포넌트는 약관을 보여주는 역할만 해야할 것 같습니다. 만약 이 컴포넌트에 체크박스가 있을 거라면 약관내용을 컴포넌트로 분리해서 책임을 나눠야 할 것 같습니다

2019-05-16 12:59 UTC, junu126 commented on natuur/src/container/Authorization/SignUp/SignUp.tsx
> +    setChecked(state);
수정이요!

2019-05-16 13:00 UTC, junu126 commented on natuur/src/App.tsx
> +            exact={true}
tslint를 재설정하고나서 tslint의 규칙에 맞도록 바꾸었습니다.

2019-05-16 13:00 UTC, junu126 commented on natuur/src/App.tsx
> +          <Route path="/intro" component={() => <Introduce />} exact={true} />
넹 수정했습니다.

2019-05-16 13:01 UTC, junu126 commented on natuur/src/container/Authorization/SignUp/SignUp.tsx
> +        updateUserEmail(value);
함수를 각각 분리해서 핸들러를 3개로 만들었습니다.

2019-05-16 13:03 UTC, junu126 commented on natuur/src/styles/Authorization/index.ts
> +  border-color: ${(props: any) => props.false && '#a7a7a7'};
styled-components에서 사용하는 모든 props에 해당하는 부분부분마다 interface를 만들어 주는게 맞을까요, 아니면 하나의 큰 interface를 만들어서 쏟아 부을까요?
@engolder

2019-05-16 13:04 UTC, junu126 commented on natuur/src/styles/Authorization/index.ts
> +export const AcceptTermsCheckBoxLabel: any = styled.label`
타입을 지정하지 않으면 에러가 발생하고 말아요.
props를 사용한 styled의 type이 궁금한데 구글링을 해도 찾기가 쉽지 않습니다..도와주세요

2019-05-16 13:05 UTC, junu126 commented on natuur/src/components/Authorization/AcceptTerms.tsx
> +  </AcceptTermsComponent>
넵 수정하도록했습니다.

2019-05-28 08:02 UTC, engolder commented on natuur/src/styles/Authorization/index.ts
> +  border-color: ${(props: any) => props.false && '#a7a7a7'};
https://www.styled-components.com/docs/api#typescript
이거 읽어보셈 뭔가 해답같은데

2019-05-29 08:08 UTC, junu126 commented on natuur/src/styles/Authorization/index.ts
> +  border-color: ${(props: any) => props.false && '#a7a7a7'};
오 ㄴㅇㅅ 한번 바꿔볼게연

2019-05-29 11:21 UTC, merged