[Accept button] common component로 button style 및 기능을 구현
Jaws-bar/Entry4.0-EntrySystem-Frontend pull request #8
Opened 2019-05-17 05:19 UTC by junu126

체크를 했을때의 버튼과 그렇지 않을때의 버튼은 styled props로 처리하였습니다.

styled props의 type와 styled component의 type도 궁굼합니다.

2019-05-17 05:22 UTC, junu126 commented
이거 stash를 잘못해서 저렇게 된 것 같은데요.

5월 17일 commit만 리뷰해주시면 될 것 같습니다.

2019-05-28 10:24 UTC, engolder requested changes
any를 사용하면 typescript의 이유가없어집니다!! styled-components의 props에 interface를 활용해봅시다. 이건 여러 방법들이 있는데 저도 계속찾아보겠습니다

2019-05-28 10:24 UTC, engolder commented on natuur/src/components/Authorization/AcceptButton.tsx
> +      next={true}
shortcut도 가독성에 문제가 없어보이는데 그러지 않는 이유가있나요??

2019-05-28 10:24 UTC, engolder commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +  updateToastr(toastrInformation: object): void;
인수의 type을 지정해주세요

2019-05-28 10:24 UTC, engolder commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +  const CreateToastr = () => {
function의 이름은 camelCase

2019-05-28 10:24 UTC, engolder commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +        onClick={() => CreateToastr()}
익명함수로 감싸줄 필요가 없어보입니다

2019-05-28 10:24 UTC, engolder commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +  const CreateToastr = () => {
렌더마다 함수를 생성하는 퍼포먼스 문제가 발생합니다 class컴포넌트 혹은 react hooks로 해결할 수 있습니다

2019-05-28 10:36 UTC, engolder requested changes

2019-05-28 10:36 UTC, engolder commented on natuur/src/styles/default/index.ts
> +    'url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGwSURBVEhLtZa9SgNBEMc9sUxxRcoUKSzSWIhXpFMhhYWFhaBg4yP
음 일단 base64를 사용하면 크기가 4/3정도 더 늘어나게 된다는 단점이있습니다. 하지만 이 이미지의 크기가 커보이진 않으니 크게 문제가 될 건 없어보입니다.
그리고 base64를 사용하더라도 png파일을 import해서 사용할 수 있습니다. 이렇게 인코딩결과를 하드코딩하는 것은 가독성에서 매우 좋지 않아보입니다. :angry:

2019-05-28 10:36 UTC, engolder commented on natuur/src/styles/default/index.ts
> +    props.toastrState === "info" &&
똑같은 코드의 반복같습니다.
```ts
`
background-image: ${() => {
  switch() {
    case: return 
  }
}
`
```
switch-case문을 사용합시다

2019-05-28 10:38 UTC, engolder approved these changes
리뷰에 도움되지 않는 커밋은 합치던지 다른 브랜치에서 해주세요
approve잘못했는데 취소 어떻게하냐 ㅋㅋ

2019-05-29 08:16 UTC, junu126 commented on natuur/src/components/Authorization/AcceptButton.tsx
> +      next={true}
tslint airbnb를 적용시켰는데 tslint가 자동으로 저렇게 바꾸어주었습니다.

2019-05-29 08:21 UTC, junu126 commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +  updateToastr(toastrInformation: object): void;
object의 타입을 정해달라는 말씀이시죠?
바꾸도록 하였습니다.

2019-05-29 09:16 UTC, junu126 commented on natuur/src/components/Authorization/AcceptDisableButton.tsx
> +  const CreateToastr = () => {
useCallback Hooks사용해서 첫 랜더시에만 함수를 생성하도록 변경하였습니다.

2019-05-29 09:19 UTC, junu126 commented on natuur/src/styles/default/index.ts
> +    'url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAGwSURBVEhLtZa9SgNBEMc9sUxxRcoUKSzSWIhXpFMhhYWFhaBg4yP
how can i use png file??

2019-05-29 11:21 UTC, merged